- name: download vault-agent to localhost
  become: false
  run_once: true
  delegate_to: localhost
  get_url:
    url: "{{ _archive_url }}"
    dest: "{{ role_path }}/files/{{ _archive }}"
    checksum: "sha256:{{ _archive_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: create vault-agent system group
  group:
    name: "{{ vault_agent_group }}"
    system: true
    state: present
  when: vault_agent_group != "root"

- name: create vault-agent system user
  user:
    name: "{{ vault_agent_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ vault_agent_group }}"
    create_home: false
    state: present
  when: vault_agent_group != "root"

- name: create vault-agent directories
  file:
    path: "{{ dir.value.path }}"
    state: directory
    owner: "{{ dir.group | default('vault') }}"
    group: "{{ dir.group | default('vault') }}"
    mode: "{{ dir.value.mode | default(755) }}"
  loop: "{{ vault_agent_dirs | dict2items }}"
  loop_control:
    loop_var: dir
    label: "{{ dir.key }}"

- name: create archive directory
  become: false
  delegate_to: localhost
  file:
    state: directory
    path: "{{ _archive_dir }}"

- name: unpack vault-agent
  become: false
  delegate_to: localhost
  unarchive:
    src: "{{ role_path }}/files/{{ _archive }}"
    dest: "{{ _archive_dir }}"
    creates: "{{ _archive_dir }}/vault"

- name: propagate vault-agent binary
  copy:
    src: "{{ _archive_dir }}/vault"
    dest: "/usr/bin/vault-agent"
    owner: root
    group: root
    mode: 0555
  notify: restart vault

- name: delete archive directory
  become: false
  run_once: true
  delegate_to: localhost
  file:
    dest: "{{ _archive_dir }}"
    state: absent
  when: not lookup("env", "MOLECULE_SCENARIO_NAME") | default("")

- name: create vault-agent config
  tags: config
  copy:
    content: "{{ vault_agent_config | to_nice_json }}"
    dest: "{{ vault_agent_dirs.main.path }}/vault-agent.json"
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    mode: 0640
  notify: restart vault-agent

- name: create vault-agent service file
  tags: config
  copy:
    content: "{{ vault_agent_service }}"
    dest: "/etc/init.d/vault-agent"
    owner: root
    group: root
    mode: 0755
  notify: restart vault-agent
  when: ansible_service_mgr == "openrc"

- name: enable vault-agent
  service:
    name: vault-agent
    enabled: true
  when: ansible_service_mgr == "openrc"

- name: create vault-agent unit file
  tags: config
  copy:
    content: "{{ vault_agent_unit }}"
    dest: "/etc/systemd/system/vault-agent.service"
    owner: root
    group: root
    mode: 0755
  notify: restart vault-agent
  when: ansible_service_mgr == "systemd"

- name: enable vault-agent
  systemd:
    name: vault-agent
    enabled: true
    daemon_reload: true
  when: ansible_service_mgr == "systemd"
